# -*- coding: utf-8 -*-
"""data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPcNFRTnDoayLUxoV4dIC89eogZXNfc1
"""

from google.colab import drive
import os

# This will pop up a window asking for permission to access your Drive
drive.mount('/content/drive')

# Set your working directory to the folder you created
path = "/content/drive/MyDrive/Nadi_Pekerja_Data"
os.chdir(path)

print("Files in your directory:")
print(os.listdir())

import pandas as pd
import numpy as np
import json
import warnings
warnings.filterwarnings('ignore')

# Lock the numbers so your dashboard doesn't change
np.random.seed(42)

print("🚀 Starting the True Unified Nadi-Pekerja Pipeline...")

# ==========================================
# 1. LOAD THE DATA
# ==========================================
df_employees = pd.read_csv('employees.csv') # Make sure this is Pohyi's Kaggle file!
df_sales = pd.read_csv('sales_orders_sample.csv')
df_inventory = pd.read_csv('inventory_movements_sample.csv')
attendance_raw = pd.read_csv('attendance_2023_2024.csv')
whatsapp_df = pd.read_csv('whatsapp_logs.csv', delimiter='|')

# ==========================================
# 2. HR LOCALIZATION
# ==========================================
print("Applying Salary Matrix...")
def localize_salary_to_rm(role_title):
    role = str(role_title).lower()
    if 'manager' in role or 'director' in role or 'head' in role: return np.random.randint(5000, 12000)
    elif 'executive' in role or 'admin' in role or 'accountant' in role or 'sales' in role: return np.random.randint(3000, 5000)
    else: return np.random.randint(1700, 2800)

df_employees['monthly_salary_rm'] = df_employees['role'].apply(localize_salary_to_rm)

# ==========================================
# 3. TASK LINKAGE
# ==========================================
print("Employee-Task Linkage...")
# A. Sales Staff Linkage
sales_roles = ['manager', 'sales', 'associate', 'cashier']
sales_staff_ids = df_employees[df_employees['role'].str.lower().str.contains('|'.join(sales_roles))]['id'].tolist()
df_sales['sst_amount_rm'] = (df_sales['gst_amount'] * 3.2).round(2)
df_sales['total_amount_rm'] = (df_sales['total_amount'] * 3.2).round(2)
if sales_staff_ids:
    df_sales['handled_by_employee_id'] = np.random.choice(sales_staff_ids, size=len(df_sales))
df_sales_clean = df_sales[['order_number', 'order_date', 'status', 'sst_amount_rm', 'total_amount_rm', 'handled_by_employee_id']]

# B. Warehouse Staff Linkage
warehouse_roles = ['warehouse', 'logistics', 'inventory', 'stock']
warehouse_staff_ids = df_employees[df_employees['role'].str.lower().str.contains('|'.join(warehouse_roles))]['id'].tolist()
df_outbound = df_inventory[df_inventory['reference_type'].str.contains('sales', case=False, na=False)].copy()
if warehouse_staff_ids:
    df_outbound['packed_by_employee_id'] = np.random.choice(warehouse_staff_ids, size=len(df_outbound))
df_logistics_clean = df_outbound[['movement_date', 'quantity', 'packed_by_employee_id']]

# ==========================================
# 4. ATTENDANCE & OVERTIME MATH
# ==========================================
print("Running Your Overtime Math...")
df_long = attendance_raw.melt(id_vars=['Date'], var_name='Employee_ID', value_name='Shift_Time').dropna()
df_long = df_long[df_long['Shift_Time'].str.contains('-', na=False)].copy()
df_long[['Clock_In', 'Clock_Out']] = df_long['Shift_Time'].str.split('-', expand=True)

df_long['In_DT'] = pd.to_datetime(df_long['Date'] + ' ' + df_long['Clock_In'], errors='coerce')
df_long['Out_DT'] = pd.to_datetime(df_long['Date'] + ' ' + df_long['Clock_Out'], errors='coerce')
df_long['Total_Hours'] = (df_long['Out_DT'] - df_long['In_DT']).dt.total_seconds() / 3600
df_long['OT_Hours'] = df_long['Total_Hours'].apply(lambda x: x - 8 if x > 8 else 0)

monthly_ot = df_long.groupby('Employee_ID')['OT_Hours'].sum().to_dict()

# ==========================================
# 5. AKTA KERJA 1955 ENGINE
# ==========================================
print("Running Your Statutory Context Engine (Akta Kerja 1955)...")
hr_data = []
for index, emp in df_employees.iterrows():
    salary = emp['monthly_salary_rm']
    emp_key = f"Person_{index}" # Mock mapping between Kaggle and Attendance data

    # EPF Math
    epf = round(salary * 0.13 if salary <= 5000 else salary * 0.12, 2)
    # Your Statutory Math
    socso = round(min(salary, 6000) * 0.0175, 2)
    eis = round(min(salary, 6000) * 0.002, 2)
    true_cost = round(salary + epf + socso + eis, 2)

    # Overtime & EA 1955 Logic (Forcing the Warehouse Anomaly)
    actual_ot = 112.5 if "Warehouse" in str(emp['role']) else monthly_ot.get(emp_key, 45.0)
    status = "EA 1955 VIOLATION" if actual_ot > 104 else "Compliant"
    warnings = [f"Logged {actual_ot} OT hours, exceeding the 104-hour limit."] if actual_ot > 104 else []

    hr_data.append({
        "id": emp['id'],
        "department_id": emp['department_id'],
        "first_name": emp['first_name'],
        "role": emp['role'],
        "monthly_salary_rm": salary,
        "actual_ot_hours_this_month": actual_ot,
        "ea_1955_compliance": {
            "status": status,
            "warnings": warnings,
            "ot_eligible": salary <= 4000,
            "true_employer_cost_rm": true_cost
        }
    })

# ==========================================
# 6. YOUR WHATSAPP LOGS
# ==========================================
print("Injecting Your Unstructured WhatsApp Context...")
bottleneck_keywords = ['sangkut', 'manual', 'lambat', 'bottleneck', 'penat', 'banyak']
evidence_logs = whatsapp_df[whatsapp_df['Message'].str.contains('|'.join(bottleneck_keywords), case=False, na=False)]
unstructured_evidence = evidence_logs.apply(lambda row: f"[{row['Timestamp']}] {row['Sender']}: {row['Message']}", axis=1).tolist()

# ==========================================
# 7. EXPORT THE MASTER JSON
# ==========================================
print("Architecting the Ultimate Nadi-Pekerja JSON...")
nadi_pekerja_ultimate_twin = {
    "metadata": {"simulation_type": "Retail_Distribution_Digital_Twin", "currency": "MYR", "tax_structure": "SST"},
    "workforce": hr_data,
    "revenue_engine": df_sales_clean.to_dict(orient='records'),
    "operational_load": df_logistics_clean.to_dict(orient='records'),
    "operational_communications": {
        "source": "WhatsApp Group: Chong Wholesale Internal",
        "bottleneck_evidence_logs": unstructured_evidence
    }
}

with open('nadi_pekerja_ultimate_twin_final.json', 'w') as f:
    json.dump(nadi_pekerja_ultimate_twin, f, indent=4)

print("✅ SUCCESS! The data is perfectly combined.")